//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic.Switch.Board.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magic.Switch.Board.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconFileNew {
            get {
                object obj = ResourceManager.GetObject("IconFileNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconFileOpen {
            get {
                object obj = ResourceManager.GetObject("IconFileOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconFileQuit {
            get {
                object obj = ResourceManager.GetObject("IconFileQuit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconFileSettings {
            get {
                object obj = ResourceManager.GetObject("IconFileSettings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconHelp {
            get {
                object obj = ResourceManager.GetObject("IconHelp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconHelpAbout {
            get {
                object obj = ResourceManager.GetObject("IconHelpAbout", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconHelpNews {
            get {
                object obj = ResourceManager.GetObject("IconHelpNews", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconHelpUpdate {
            get {
                object obj = ResourceManager.GetObject("IconHelpUpdate", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Magic_Switch_Board {
            get {
                object obj = ResourceManager.GetObject("Magic_Switch_Board", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        internal static string ViewModel_Display_Name_Application_Version {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Application_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string ViewModel_Display_Name_Channels {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration version.
        /// </summary>
        internal static string ViewModel_Display_Name_Configuration_Version {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Configuration_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string ViewModel_Display_Name_Id {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string ViewModel_Display_Name_Input {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops.
        /// </summary>
        internal static string ViewModel_Display_Name_Loops {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Loops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type.
        /// </summary>
        internal static string ViewModel_Display_Name_MessageType {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi channel.
        /// </summary>
        internal static string ViewModel_Display_Name_MidiChannel {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_MidiChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ViewModel_Display_Name_Name {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string ViewModel_Display_Name_Number {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string ViewModel_Display_Name_Output {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        internal static string ViewModel_Display_Name_Switches {
            get {
                return ResourceManager.GetString("ViewModel_Display_Name_Switches", resourceCulture);
            }
        }
    }
}
