//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic.Switch.Board.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magic.Switch.Board.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs that describe an unrecoverable application or system crash, or a catastrophic failure that requires immediate attention..
        /// </summary>
        public static string Enum_LogLevel_Critical_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_Critical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs that are used for interactive investigation during development. These logs should primarily contain information useful for debugging and have no long-term value..
        /// </summary>
        public static string Enum_LogLevel_Debug_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_Debug_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs that highlight when the current flow of execution is stopped due to a failure. These should indicate a failure in the current activity, not an application-wide failure..
        /// </summary>
        public static string Enum_LogLevel_Error_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs that track the general flow of the application. These logs should have long-term value..
        /// </summary>
        public static string Enum_LogLevel_Information_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_Information_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not used for writing log messages. Specifies that a logging category should not write any messages..
        /// </summary>
        public static string Enum_LogLevel_None_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_None_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs that contain the most detailed messages. These messages may contain sensitive application data. These messages are disabled by default and should never be enabled in a production environment..
        /// </summary>
        public static string Enum_LogLevel_Trace_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_Trace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs that highlight an abnormal or unexpected event in the application flow, but do not otherwise cause the application execution to stop..
        /// </summary>
        public static string Enum_LogLevel_Warning_Description {
            get {
                return ResourceManager.GetString("Enum_LogLevel_Warning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 1.
        /// </summary>
        public static string Enum_LoopChannels_1 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 2.
        /// </summary>
        public static string Enum_LoopChannels_2 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 3.
        /// </summary>
        public static string Enum_LoopChannels_3 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 4.
        /// </summary>
        public static string Enum_LoopChannels_4 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 5.
        /// </summary>
        public static string Enum_LoopChannels_5 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 6.
        /// </summary>
        public static string Enum_LoopChannels_6 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 7.
        /// </summary>
        public static string Enum_LoopChannels_7 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Channel 8.
        /// </summary>
        public static string Enum_LoopChannels_8 {
            get {
                return ResourceManager.GetString("Enum_LoopChannels_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 1.
        /// </summary>
        public static string Enum_MidiChannel_1 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 10.
        /// </summary>
        public static string Enum_MidiChannel_10 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 11.
        /// </summary>
        public static string Enum_MidiChannel_11 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 12.
        /// </summary>
        public static string Enum_MidiChannel_12 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 13.
        /// </summary>
        public static string Enum_MidiChannel_13 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 14.
        /// </summary>
        public static string Enum_MidiChannel_14 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 15.
        /// </summary>
        public static string Enum_MidiChannel_15 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 16.
        /// </summary>
        public static string Enum_MidiChannel_16 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 2.
        /// </summary>
        public static string Enum_MidiChannel_2 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 3.
        /// </summary>
        public static string Enum_MidiChannel_3 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 4.
        /// </summary>
        public static string Enum_MidiChannel_4 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 5.
        /// </summary>
        public static string Enum_MidiChannel_5 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 6.
        /// </summary>
        public static string Enum_MidiChannel_6 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 7.
        /// </summary>
        public static string Enum_MidiChannel_7 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 8.
        /// </summary>
        public static string Enum_MidiChannel_8 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Channel 9.
        /// </summary>
        public static string Enum_MidiChannel_9 {
            get {
                return ResourceManager.GetString("Enum_MidiChannel_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Change Message.
        /// </summary>
        public static string Enum_MidiMessageType_CCM {
            get {
                return ResourceManager.GetString("Enum_MidiMessageType_CCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Change Message.
        /// </summary>
        public static string Enum_MidiMessageType_PCM {
            get {
                return ResourceManager.GetString("Enum_MidiMessageType_PCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 1.
        /// </summary>
        public static string Enum_SwitchChannels_1 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 2.
        /// </summary>
        public static string Enum_SwitchChannels_2 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 3.
        /// </summary>
        public static string Enum_SwitchChannels_3 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 4.
        /// </summary>
        public static string Enum_SwitchChannels_4 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 5.
        /// </summary>
        public static string Enum_SwitchChannels_5 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 6.
        /// </summary>
        public static string Enum_SwitchChannels_6 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 7.
        /// </summary>
        public static string Enum_SwitchChannels_7 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Channel 8.
        /// </summary>
        public static string Enum_SwitchChannels_8 {
            get {
                return ResourceManager.GetString("Enum_SwitchChannels_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during deserialisation. Unkown attribute found. Name: &apos;{0}&apos; at line: {1} and position: {2}..
        /// </summary>
        public static string Error_Xml_Unknown_Attribute {
            get {
                return ResourceManager.GetString("Error_Xml_Unknown_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during deserialisation. Unkown element found. Name: &apos;{0}&apos; at line: {1} and position: {2}..
        /// </summary>
        public static string Error_Xml_Unknown_Element {
            get {
                return ResourceManager.GetString("Error_Xml_Unknown_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during deserialisation. Unkown node found. Name: &apos;{0}&apos; of type: &apos;{1}&apos;.
        /// </summary>
        public static string Error_Xml_Unknown_Node {
            get {
                return ResourceManager.GetString("Error_Xml_Unknown_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory could not be found..
        /// </summary>
        public static string File_Service_Error_Directory {
            get {
                return ResourceManager.GetString("File_Service_Error_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be found..
        /// </summary>
        public static string File_Service_Error_File {
            get {
                return ResourceManager.GetString("File_Service_Error_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was created..
        /// </summary>
        public static string File_Service_File_Created {
            get {
                return ResourceManager.GetString("File_Service_File_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; has been deleted..
        /// </summary>
        public static string File_Service_File_Deleted {
            get {
                return ResourceManager.GetString("File_Service_File_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; has been loaded..
        /// </summary>
        public static string File_Service_File_Read {
            get {
                return ResourceManager.GetString("File_Service_File_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in a range between {2} and {1}..
        /// </summary>
        public static string Model_Field_Range_Generic {
            get {
                return ResourceManager.GetString("Model_Field_Range_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field..
        /// </summary>
        public static string Model_Field_Required_Generic {
            get {
                return ResourceManager.GetString("Model_Field_Required_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {2} and {1} characters long..
        /// </summary>
        public static string Model_Field_StringLength_Generic {
            get {
                return ResourceManager.GetString("Model_Field_StringLength_Generic", resourceCulture);
            }
        }
    }
}
