name: docs

on:
  push:
    branches: [ main ]

jobs:
    publish-docs:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3

      - name: DocFx Setup
        run: dotnet tool update -g docfx

      - name: Run DocFx
        run: docfx docs/docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site